FireTwin/Controllers/ShopController.cs
using System.Threading.Tasks;
using DynEntity;
using FireTwin.Models;
using Microsoft.AspNetCore.Mvc;

namespace FireTwin.Controllers
{
    public class ShopController : Controller
    {
        private readonly DataRepository<Product> _prod;
        public ShopController(DataRepository<Product> prod)
        {

            //_products = db.GetInstance<Product>();
            _prod = prod;
        }
        public async Task<IActionResult> Index()
        {
            var hh = _prod.All();
            return View();
        }

        public async Task<IActionResult> Details(int id)
        {
            Product model = _prod.Find(id);
            return View(model);
        }
    }
}

FireTwin/Controllers/ShoppingCartController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using DynEntity;
using FireTwin.Extras;
using FireTwin.Models;
using Microsoft.AspNetCore.Mvc;

namespace FireTwin.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly DataRepository<Cart> _carts;
        private readonly DataRepository<Product> _products;
        private const string SessionCartKey = "Cart";
        public ShoppingCartController(DataRepository<Cart> carts, DataRepository<Product> products)
        {
            _carts = carts;
            //_carts = db.GetInstance<Cart>();
            _products = products;
        }

        public async Task<IActionResult> Index()
        {
            Cart cart = await GetCartAsync();
            var products = cart.Products;
            return View(products);
        }

        [HttpPost]
        public async Task<int> AddToCart(int productId)
        {
            Cart cart = await GetCartAsync();
            Product product = _products.Find(productId);
            if (product != null)
            {
                cart.Products.Add(product);
                await SaveCartAsync(cart);
            }
            return cart.Products.Count(); ;
        }

        public async Task<int> CartCount()
        {
            Cart cart = await GetCartAsync();
            return cart.Products.Count();
        }

        private async Task<Cart> GetCartAsync()
        {
            Cart cart = null;
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                string userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                IEnumerable<Cart> carts = _carts.All();
                cart = carts.FirstOrDefault(c => c.UserId == userId);
                if (cart == null)
                {
                    cart = new Cart() { UserId = userId, Products = new List<Product>() };
                    cart.Id =  _carts.Add(cart);
                }
            }
            else
            {
                cart = HttpContext.Session.GetObjectFromJson<Cart>(SessionCartKey);
                if (cart == null)
                {
                    cart = new Cart() { Products = new List<Product>() };
                    HttpContext.Session.SetObjectAsJson(SessionCartKey, cart);
                }
            }


            return cart;
        }

        private async Task<bool> SaveCartAsync(Cart cart)
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                _carts.Update(cart);
            }
            else
            {
                HttpContext.Session.SetObjectAsJson(SessionCartKey, cart);
            }
            return true;
        }

    }
}

FireTwin/Views/Shared/_AdminLayout.cshtml
@using FireTwin.Extras.Security
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@{
    string controllerName = this.ViewContext.RouteData.Values["controller"].ToString();
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="~/css/admin.css" rel="stylesheet" />
</head>
<body>
    <div class="flex">

        <div class="side-navigation flex flex-column">
            <a class="navigation-item @(controllerName == "Categories" ? "navigation-item-active": "") " asp-controller="Categories" asp-action="Index">Categories</a>
            <a class="navigation-item @(controllerName == "Products" ? "navigation-item-active": "") " asp-controller="Products" asp-action="Index">Products</a>
            <a class="navigation-item @(controllerName == "Folders" ? "navigation-item-active": "") " asp-controller="Folders" asp-action="Index">Folders</a>

            <a class="navigation-item flex-bottom" asp-controller="Shop" asp-action="Index">Shop</a>
        </div>
        <div class="body-content">
            @RenderBody()
        </div>
    </div>
    <hr />
    <footer>
        <p>&copy; 2019 - FireTwin</p>
    </footer>




    @Html.RenderTsScripts("_AdminLayout")

    @RenderSection("Scripts", required: false)

</body>
</html>

FireTwin/Views/Shared/_Layout.cshtml
@using FireTwin.Extras.Security
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FireTwin</title>
    @*<link href="~/bootstrap-3.3.7-dist/css/bootstrap.css" rel="stylesheet" />*@

    <link href="~/css/webfonts/all.css" rel="stylesheet" />
    <link href="~/css/main.css" rel="stylesheet" />
    @*<script src="~/jquery-3.3.1.js"></script>*@
    @*<script src="~/bootstrap-3.3.7-dist/js/bootstrap.js"></script>*@
</head>
<body>
    <nav class="navbar ">
        <div class="container flex flex-margin-sides-mid">

            <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            <a asp-area="" asp-controller="Shop" asp-action="Index">Shop</a>
            <a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
            @if ((await AuthorizationService.AuthorizeAsync(
User,
Security.Policies.AdminOnly.ToText()
)).Succeeded)
            {
                <a asp-area="" asp-controller="Folders" asp-action="Index">Folders</a>
                <a asp-area="" asp-controller="Products" asp-action="Index">Products</a>
            }

            <div class="flex flex-margin-sides-mid flex-right">
                <div>
                    <a asp-controller="ShoppingCart" asp-action="Index" class="shopping-cart">
                        <i class="fas fa-shopping-cart fa-2x" style="color:white">
                        </i>
                        <div class="shopping-cart-indicator">
                            <div class="shopping-cart-count"></div>
                            <div class="shopping-cart-background">
                            </div>
                        </div>

                    </a>
                </div>
                <div>
                    <partial name="_LoginPartial" />
                </div>

            </div>
        </div>

    </nav>
    <partial name="_CookieConsentPartial" />
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - FireTwin</p>
        </footer>
    </div>
    @Html.RenderTsScripts("_Layout")
    @RenderSection("Scripts", required: false)

</body>
</html>

FireTwin/Views/Shared/_Layout_Template.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FireTwin</title>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">FireTwin</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - FireTwin</p>
        </footer>
    </div>
    @*@{ string scriptPath = Html.GetScriptPath();}
    @if (scriptPath != null)
    {
        <script>
            require(["@scriptPath"],
                function (script) {


                }
            );
        </script>
    }*@
</body>
</html>